----------------------------------------------------------------
-- this is just a demostration of the org-mode and the babel  --
-- the source code contains nothing but four lines of comments --
----------------------------------------------------------------
